<?xml version="1.0"?>
<robot name="lower_limb_exoskeleton" xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:property name="camera_link_dim" value="0.05" />

<link name="d435_front">
  <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="${camera_link_dim/2} ${camera_link_dim} ${camera_link_dim/2}"/>
    </geometry>
  </collision>

  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="${camera_link_dim/4} ${camera_link_dim} ${camera_link_dim/2}"/>
    </geometry>
    <material name="red"/>
  </visual>

  <inertial>
    <mass value="1e-5" />
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
  </inertial>
</link>

<joint name="d435_front_joint" type="fixed">
  <axis xyz="0 1 0" />
  <origin xyz="${thigh_w/2} 0 ${-thigh_l/2}" rpy="0 ${PI/4} 0"/>
  <parent link="l_thigh_link"/>
  <child link="d435_front"/>
</joint>

  <gazebo reference="d435_front">
    <sensor type="depth" name="d435_front">
      <always_on>true</always_on>
      <visualize>false</visualize>
      <camera>
          <horizontal_fov>1.3439</horizontal_fov>
          <image>
              <width>1920</width>
              <height>1080</height>
              <format>R8G8B8</format>
          </image>
          <depth_camera></depth_camera>
          <clip>
              <near>0.03</near>
              <far>100</far>
          </clip>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_openni_kinect.so">
        <baseline>0.2</baseline>
        <alwaysOn>true</alwaysOn>
        <updateRate>30.0</updateRate>
        <cameraName>d435_front</cameraName>
        <frameName>d435_front</frameName>
        <imageTopicName>d435_front/rgb/image_raw</imageTopicName>
        <depthImageTopicName>d435_front/depth/image_raw</depthImageTopicName>
        <pointCloudTopicName>d435_front/depth/points</pointCloudTopicName>
        <cameraInfoTopicName>d435_front/rgb/camera_info</cameraInfoTopicName>
        <depthImageCameraInfoTopicName>d435_front/depth/camera_info</depthImageCameraInfoTopicName>
        <pointCloudCutoff>0.1</pointCloudCutoff>
            <hackBaseline>0.01</hackBaseline>
            <distortionK1>0.0</distortionK1>
            <distortionK2>0.0</distortionK2>
            <distortionK3>0.0</distortionK3>
            <distortionT1>0.0</distortionT1>
            <distortionT2>0.0</distortionT2>
        <CxPrime>0.0</CxPrime>
        <Cx>0.0</Cx>
        <Cy>0.0</Cy>
        <focalLength>0</focalLength>
        <hackBaseline>0</hackBaseline>
      </plugin>
    </sensor>
  </gazebo>

  <link name="d435_back">
  <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="${camera_link_dim/2} ${camera_link_dim} ${camera_link_dim/2}"/>
    </geometry>
  </collision>

  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="${camera_link_dim/4} ${camera_link_dim} ${camera_link_dim/2}"/>
    </geometry>
    <material name="red"/>
  </visual>

  <inertial>
    <mass value="1e-5" />
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
  </inertial>
</link>

<joint name="d435_back_joint" type="fixed">
  <axis xyz="0 1 0" />
  <origin xyz="${-thigh_w/2} 0 ${-thigh_l/2}" rpy="0 0 ${PI}"/>
  <parent link="l_thigh_link"/>
  <child link="d435_back"/>
</joint>

  <gazebo reference="d435_back">
    <sensor type="depth" name="d435_back">
      <always_on>true</always_on>
      <visualize>false</visualize>
      <camera>
          <horizontal_fov>1.3439</horizontal_fov>
          <image>
              <width>1920</width>
              <height>1080</height>
              <format>R8G8B8</format>
          </image>
          <depth_camera></depth_camera>
          <clip>
              <near>0.03</near>
              <far>100</far>
          </clip>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_openni_kinect.so">
        <baseline>0.2</baseline>
        <alwaysOn>true</alwaysOn>
        <updateRate>30.0</updateRate>
        <cameraName>d435_back</cameraName>
        <frameName>d435_back</frameName>
        <imageTopicName>d435_back/rgb/image_raw</imageTopicName>
        <depthImageTopicName>d435_back/depth/image_raw</depthImageTopicName>
        <pointCloudTopicName>d435_back/depth/points</pointCloudTopicName>
        <cameraInfoTopicName>d435_back/rgb/camera_info</cameraInfoTopicName>
        <depthImageCameraInfoTopicName>d435_back/depth/camera_info</depthImageCameraInfoTopicName>
        <pointCloudCutoff>0.1</pointCloudCutoff>
            <hackBaseline>0.01</hackBaseline>
            <distortionK1>0.0</distortionK1>
            <distortionK2>0.0</distortionK2>
            <distortionK3>0.0</distortionK3>
            <distortionT1>0.0</distortionT1>
            <distortionT2>0.0</distortionT2>
        <CxPrime>0.0</CxPrime>
        <Cx>0.0</Cx>
        <Cy>0.0</Cy>
        <focalLength>0</focalLength>
        <hackBaseline>0</hackBaseline>
      </plugin>
    </sensor>
  </gazebo>



  <gazebo reference="d435_front">
        <gravity>true</gravity>
        <sensor name="d435_front" type="imu">
        <always_on>true</always_on>
        <update_rate>100</update_rate>
        <visualize>true</visualize>
        <topic>d435_front/imu_data</topic>
        <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
            <topicName>d435_front/imu_data</topicName>
            <bodyName>d435_front_imu</bodyName>
            <updateRateHZ>10.0</updateRateHZ>
            <gaussianNoise>0.0</gaussianNoise>
            <xyzOffset>0 0 0</xyzOffset>
            <rpyOffset>0 0 0</rpyOffset>
            <frameName>d435_front_imu</frameName>
            <initialOrientationAsReference>false</initialOrientationAsReference>
        </plugin>
        <pose>0 0 0 0 0 0</pose>
        </sensor>
    </gazebo>
 
</robot>